service: huggingface-on-lambda

provider:
  name: aws
  region: eu-west-1 
  memorySize: 1024 
  timeout: 30 

functions:
  huggingface:
    # paste the <image-uri>@<image-digest>
    image: 077590795309.dkr.ecr.eu-west-1.amazonaws.com/huggingface-on-lambda@sha256:af502889a2e227900cd62081e8df9995feaec81f7dfa1de5955f991d13bba7a5
    events:
      - http:
          path: prediction # http path
          method: post # http method

